mysql:
  env_file:
    - ${ENV_FILE:-.env.local}
  profiles: ["with-db"]
  image: mysql:8.4.0
  command: >
    --default-authentication-plugin=mysql_native_password
    --bind-address=0.0.0.0
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_unicode_ci
    --init-file=/docker-entrypoint-initdb.d/init.sql
  volumes:
    - ./db_data:/var/lib/mysql
    - ./table_schema.sql:/docker-entrypoint-initdb.d/table_schema.sql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  environment:
    - MYSQL_DATABASE=${RDS_DATABASE:-btc_stamps}
    - MYSQL_ROOT_PASSWORD=${RDS_PASSWORD:-root}
    - MYSQL_USER=${RDS_USER}
    - MYSQL_PASSWORD=${RDS_PASSWORD}
    - MYSQL_ROOT_HOST=%
  ports:
    - "3306:3306" 

indexer:
  build:
    context: .
    dockerfile: Dockerfile
    args:
      PYTHON_VERSION: 3.12
      INSTALL_DEV: "true"
  image: ${IMAGE_NAME:-btc_stamps/indexer:local-dev}
  labels:
    com.docker.compose.environment: "local-development"
    com.docker.compose.project: "indexer-local"
  network_mode: ${NETWORK_MODE:-host}
  env_file:
    - ${ENV_FILE:-.env.local}
  environment:
    - ENV_FILE=${ENV_FILE:-.env.local}
    - DEBUG=1
    - RDS_DATABASE=${RDS_DATABASE:-btc_stamps}
    - RDS_PASSWORD=${RDS_PASSWORD:-root}
    - RDS_USER=${RDS_USER}
    - RDS_PASSWORD=${RDS_PASSWORD}
    - RDS_ROOT_HOST=%
    - MYSQL_DATABASE=${RDS_DATABASE:-btc_stamps}
    - MYSQL_ROOT_PASSWORD=${RDS_PASSWORD:-root}
    - MYSQL_USER=${RDS_USER}
    - MYSQL_PASSWORD=${RDS_PASSWORD}
    - MYSQL_ROOT_HOST=%
  ports:
    - "3306:3306" 