version: '3.8'

services:
  db:
    image: mysql:latest
    platform: ${DOCKER_PLATFORM}
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./table_schema.sql:/docker-entrypoint-initdb.d/table_schema.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: btc_stamps
      MYSQL_USER: ja
      MYSQL_PASSWORD: asdfeadsadfawewefwq23d
      GRAFANA_USER: grafana
      GRAFANA_PASSWORD: GrafanaPassword
    command: --bind-address=0.0.0.0 --innodb_data_file_path=ibdata1:10M:autoextend
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - db
    ports:
      - "3333:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=GrafanaPassword
      - GF_USERS_ALLOW_SIGN_UP=false

  app:
    build: .
    command:  dockerize -wait tcp://db:3306 -timeout 5m python3 start.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - RDS_HOSTNAME=db
      - RDS_USER=ja
      - RDS_PASSWORD=asdfeadsadfawewefwq23d
      - RDS_DATABASE=btc_stamps
      - QUICKNODE_URL=restless-fittest-cloud.btc.discover.quiknode.pro
      - RPC_USER=rpc
      - RPC_PASSWORD=rpc
      - RPC_TOKEN=e015a6e08137eeb3cb9bfb2daba282bbcddd2d6e
volumes:
  db_data:
  grafana_data:
