repos:
  - repo: local
    hooks:
      - id: run-checks
        name: Run Checks
        entry: bash -c 'cd indexer && poetry run run_checks'
        language: system
        types: [python]
        args: ['--no-stash']