version: '3.8'

services:
  db:
    image: mysql:8.2.0
    platform: ${DOCKER_PLATFORM}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ../indexer/table_schema.sql:/docker-entrypoint-initdb.d/table_schema.sql
    restart: always
    env_file:
      - .env.mysql
    command: --bind-address=0.0.0.0 --innodb_data_file_path=ibdata1:10M:autoextend
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "3030:8080"

  grafana:
    image: grafana/grafana:10.2.3
    depends_on:
      - db
    ports:
      - "3333:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env.grafana

  indexer:
    build: ../indexer
    command:  dockerize -wait tcp://db:3306 -timeout 5m python3 start.py
    volumes:
      - ../indexer:/usr/src/app
      - ../files:/usr/src/app/files
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../indexer/.env
  app:
    build:
      context: ../app
    volumes:
      - ../files:/app/static/stamps
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - ../app/.env
      

volumes:
  db_data:
  grafana_data:
  files:
