#!/usr/bin/env python3
"""Export a partner-distributable DB bootstrap bundle.

Uses ``mysqldump`` to write a stream of consensus + reference tables —
filtered to ``block_index <= TARGET_BLOCK`` for block-keyed tables — and
optionally pipes the output through ``zstd -19`` for compact storage.

NOT to be confused with ``tools/export_bootstrap.py``, which exports the
small reference CSVs (``creator.csv``, ``srcbackground.csv``) that ship
with the repo. That one is for repo maintenance; this one produces the
multi-hundred-MB DB snapshot for partners.

Distribute the resulting artifact via S3 (e.g. ``s3://stampchain/stamps/
bootstrap/``) or GitHub Releases — operator's choice. The indexer
consumes it via ``BOOTSTRAP_FILE`` (local path); see docs/BOOTSTRAP.md.

Usage:
    poetry run python tools/export_db_bootstrap.py \\
        --target-block 796000 \\
        --out bootstrap_796000.sql.zst
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime, timezone

# Tables to include. Split into:
# - BLOCK_KEYED: filtered with --where="block_index <= N"
# - REFERENCE:   dumped in full (no row filter)
#
# Excluded — derived state, rebuilt by initialize() after import:
#   balances        (rebuild_balances reconstructs from SRC20Valid)
#   owners          (rebuild_owners reconstructs from SRC101Valid)
#
# Excluded — regenerated by market-data scheduler post-import:
#   stamp_market_data, src20_market_data, stamp_holder_cache,
#   collection_market_data, market_data_sources, stamp_sales_history

BLOCK_KEYED_TABLES = [
    "blocks",
    "transactions",
    "StampTableV4",
    "SRC20",
    "SRC20Valid",
    "SRC101",
    "SRC101Valid",
    "src101price",
    "recipients",
    "reorg_events",
]

REFERENCE_TABLES = [
    "creator",
    "srcbackground",
    "collections",
    "collection_creators",
    "collection_stamps",
    "s3objects",
    "node_version_history",
    "src20_metadata",
]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Export DB bootstrap bundle")
    p.add_argument("--target-block", type=int, required=True, help="Highest block_index to include")
    p.add_argument("--out", required=True, help="Output path (.sql or .sql.zst)")
    p.add_argument("--no-compress", action="store_true", help="Skip zstd compression even if .sql.zst")
    p.add_argument("--zstd-level", type=int, default=19, help="zstd level (default 19)")
    p.add_argument("--host", default=os.environ.get("RDS_HOSTNAME"))
    p.add_argument("--port", default=os.environ.get("RDS_PORT", "3306"))
    p.add_argument("--user", default=os.environ.get("RDS_USER"))
    p.add_argument("--password", default=os.environ.get("RDS_PASSWORD"))
    p.add_argument("--database", default=os.environ.get("RDS_DATABASE", "btc_stamps"))
    return p.parse_args()


def _common_dump_args(args: argparse.Namespace) -> list:
    return [
        "mysqldump",
        f"--host={args.host}",
        f"--port={args.port}",
        f"--user={args.user}",
        f"--password={args.password}",
        "--single-transaction",  # consistent snapshot without locking
        "--quick",  # stream rows instead of buffering
        "--no-create-db",  # don't emit CREATE DATABASE
        "--no-tablespaces",  # avoid PROCESS-privilege query on managed MySQL
        "--routines=FALSE",
        "--triggers=FALSE",
        "--default-character-set=utf8mb4",
        "--set-gtid-purged=OFF",
        "--column-statistics=0",  # MySQL 8 quirk — avoid table-stats query
    ]


def _header(target_block: int) -> bytes:
    return (
        f"-- btc_stamps bootstrap bundle\n"
        f"-- target_block: {target_block}\n"
        f"-- exported_at:  {datetime.now(timezone.utc).isoformat()}\n"
        f"-- block-keyed:  {','.join(BLOCK_KEYED_TABLES)}\n"
        f"-- reference:    {','.join(REFERENCE_TABLES)}\n"
        f"-- excluded:     market_data tables (regenerated post-import)\n\n"
    ).encode()


def export(args: argparse.Namespace) -> int:
    if not args.host or not args.user:
        print("error: RDS_HOSTNAME / RDS_USER must be set (env or --host/--user)", file=sys.stderr)
        return 2

    compress = args.out.endswith(".sql.zst") and not args.no_compress
    sink: subprocess.Popen | None = None
    out_fd = None

    if compress:
        out_fd = open(args.out, "wb")
        sink = subprocess.Popen(["zstd", f"-{args.zstd_level}", "-T0", "-q"], stdin=subprocess.PIPE, stdout=out_fd)
        out_stream = sink.stdin
    else:
        out_fd = open(args.out, "wb")
        out_stream = out_fd

    assert out_stream is not None
    try:
        out_stream.write(_header(args.target_block))

        # 1. Block-keyed tables — bounded dump.
        for table in BLOCK_KEYED_TABLES:
            print(f"  dumping {table} (block_index <= {args.target_block})…", file=sys.stderr)
            cmd = _common_dump_args(args) + [
                f"--where=block_index <= {args.target_block}",
                args.database,
                table,
            ]
            rc = subprocess.run(cmd, stdout=out_stream).returncode
            if rc != 0:
                print(f"error: mysqldump {table} failed (rc={rc})", file=sys.stderr)
                return rc

        # 2. Reference tables — full dump.
        for table in REFERENCE_TABLES:
            print(f"  dumping {table} (full)…", file=sys.stderr)
            cmd = _common_dump_args(args) + [args.database, table]
            rc = subprocess.run(cmd, stdout=out_stream).returncode
            if rc != 0:
                print(f"error: mysqldump {table} failed (rc={rc})", file=sys.stderr)
                return rc
    finally:
        if sink:
            assert sink.stdin is not None
            sink.stdin.close()
            sink.wait()
        if out_fd:
            out_fd.close()

    size_mb = os.path.getsize(args.out) / (1024**2)
    print(f"done: {args.out} ({size_mb:.1f} MB)", file=sys.stderr)
    return 0


def main() -> int:
    return export(parse_args())


if __name__ == "__main__":
    sys.exit(main())
