src101_variations_data = [
    {
        "description": "1.Basic SRC-101 token deployment",
        "src101JsonString": """{
            "p":"src-101",
            "op":"deploy",
            "name":"TEST",
            "lim":"10",
            "root":"btc",
            "owner":"mowS8WALGykeRNvgEsnbXpd1DZY55sWvEu",
            "rec":["mrkZu7YtBW3udp1a7vHtq9PeKQNgraTLzn","mjg7b3WktK67qh85t42NcMyXe2cMxNpQaM","mragE3E64YCyoFnfj3qJbJG15YFYgosCn4"],
            "tick":"BNS",
            "pri":"https://github.com/BTC_STAMP/src101/price.csv",
            "desc":"Bitname Service powered by BTC stamp.",
            "mintstart":"0",
            "mintend":"18446744073709551615",
            "wll":"https://github.com/BTC_STAMP/src101/whitelist.csv"
            }""",
        "expectedOutcome": {
            "stamp_success": True,
            "src20_success": False,
            "src101_success": True,
            "message": "SRC-101 deploy",
        },
        "source": "",
        "destination": "",
        "destination_nvalue": "",
        "btc_amount": 0.0,
        "fee": 0.0,
        "decoded_tx": "{}",
        "keyburn": 1,
        "tx_index": 0,
        "block_index": 0,
        "block_time": 0,
        "block_timestamp": 0,
        "is_op_return": False,
        "valid_stamps_in_block": [],
        "processed_src20_in_block": [],
        "p2wsh_data": None,
        "tx_hash": "dummy_tx_hash",
    },
    {
        "description": "1.Basic SRC-101 token deployment",
        "src101JsonString": """ {
            "p":"src-102",
            "op":"deploy",
            "name":"TEST",
            "lim":"10",
            "owner":"mowS8WALGykeRNvgEsnbXpd1DZY55sWvEu",
            "rec":["mrkZu7YtBW3udp1a7vHtq9PeKQNgraTLzn","mjg7b3WktK67qh85t42NcMyXe2cMxNpQaM","mragE3E64YCyoFnfj3qJbJG15YFYgosCn4"],
            "tick":"BNS",
            "pri":"30769",
            "desc":"Bitname Service powered by BTC stamp.",
            "mintstart":"0",
            "mintend":"18446744073709551615",
            "wll":"https://github.com/BTC_STAMP/src101/whitelist.csv"
        }""",
        "expectedOutcome": {
            "stamp_success": False,
            "src20_success": False,
            "src101_success": False,
            "message": "SRC-101 deploy",
        },
        "source": "",
        "destination": "",
        "destination_nvalue": "",
        "btc_amount": 0.0,
        "fee": 0.0,
        "decoded_tx": "{}",
        "keyburn": 1,
        "tx_index": 0,
        "block_index": 0,
        "block_time": 0,
        "block_timestamp": 0,
        "is_op_return": False,
        "valid_stamps_in_block": [],
        "processed_src20_in_block": [],
        "p2wsh_data": None,
        "tx_hash": "dummy_tx_hash",
    },
]
