name: Build Deno on Pull Request

on:
  pull_request:
    branches: [ dev, main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: 1.x

      - name: Build Deno App
        run: |
          cd app
          deno run -A dev.ts build
