name: Bump version
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [closed]
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Type of version to bump (major, minor, patch, build, release)'
        required: true
        default: 'patch'
      preRelease:
        description: 'Mark as a pre-release version? (true/false)'
        required: false
        default: 'false'

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)) && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
    permissions:
      contents: write
      packages: write
    env:
      GIT_USER_NAME: GitHub Action
      GIT_USER_EMAIL: action@github.com
      SKIP: 'false'
      NEW_VERSION: ''
      hash: ''
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check if last commit was made by GitHub Actions
        id: check_user
        run: |
          if git log -1 --pretty=format:'%ae' | grep -q "${{ env.GIT_USER_EMAIL }}"; then
            echo "Last commit was made by GitHub Actions. Skipping workflow."
            echo "SKIP=true" >> $GITHUB_ENV
          else
            echo "Last commit was not made by GitHub Actions. Running workflow."
            echo "SKIP=false" >> $GITHUB_ENV
          fi

      - name: Check for skip keyword in commit message
        id: check-skip
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
          printf 'COMMIT_MESSAGE=%s\n' "$COMMIT_MESSAGE" >> $GITHUB_ENV
          if [[ "$COMMIT_MESSAGE" == *"[skip version]"* ]]; then
            printf 'SKIP=true\n' >> $GITHUB_ENV
          fi

      - name: Set up Python
        if: env.SKIP == 'false'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: env.SKIP == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Configure Git
        if: env.SKIP == 'false'
        run: |
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git

      - name: Get current commit hash
        if: env.SKIP == 'false'
        id: get_commit
        run: printf 'hash=%s\n' "$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Bump version for dev branch
        if: env.SKIP == 'false' && github.ref == 'refs/heads/dev'
        run: |
          bump2version build --config-file .bumpversion.dev.cfg --verbose --allow-dirty
          printf 'NEW_VERSION=%s\n' "$(cat VERSION)" >> $GITHUB_ENV

      - name: Bump version for main branch
        if: env.SKIP == 'false' && github.ref == 'refs/heads/main'
        run: |
          bump2version patch --config-file .bumpversion.main.cfg --verbose --allow-dirty
          printf 'NEW_VERSION=%s\n' "$(cat VERSION)" >> $GITHUB_ENV

      - name: Commit and push changes if new version
        if: env.SKIP == 'false' && env.NEW_VERSION
        run: |
          if [ "$(git rev-parse HEAD)" != "${{ env.hash }}" ]; then
            git push origin HEAD:${{ github.ref }}
            git push origin --tags
          else
            echo "No new commit created, so no push."
          fi

      - name: Create Release
        if: env.SKIP == 'false' && env.NEW_VERSION
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: ${{ github.ref == 'refs/heads/dev' }}

  manual-versioning:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version
      
      - name: Bump version manually
        run: |
          bump2version ${{ github.event.inputs.versionType }} --verbose --allow-dirty
          if [ "${{ github.event.inputs.preRelease }}" == "true" ]; then
            bump2version release --new-version $(cat VERSION)+canary.0 --verbose --allow-dirty
          fi
      
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
          git push origin --tags