name: Deno Check

on:
  workflow_call:

jobs:
  deno-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: 1.x

      - name: Build Deno App
        run: |
          deno run -A dev.ts build
        working-directory: ./app