name: Deno and Node.js Check

on:
  workflow_call:

jobs:
  deno-and-nodejs-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: 1.x

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./app
  

      - name: Build Deno App
        run: |
          deno run -A dev.ts build
        working-directory: ./app