name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options: [production, staging]
      skip_tests:
        type: boolean
        default: false

jobs:
  test:
    if: ${{ !inputs.skip_tests }}
    uses: ./.github/workflows/build-test.yml
    with:
      environment: ${{ inputs.environment }}

  push_to_registry:
    needs: test
    if: ${{ always() && (inputs.skip_tests || success()) }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: btc_stamps
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: btc_stamps/indexer
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=sha,prefix=,suffix=,format=short
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./indexer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'btc_stamps/indexer:${{ inputs.tag }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: sbom.spdx.json