name: PR Workflow

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  deno-job:
    uses: ./.github/workflows/deno-check.yml

  python-job:
    needs: deno-job
    uses: ./.github/workflows/python-check.yml
