name: Python Check

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  python-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    env:
      USE_TEST_TX_HEX: '1'
      TESTING: '1'
      USE_TEST_DB: '1'
      MOCK_DB: '1'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "indexer/src/rust_parser -> target"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true
          poetry install
        working-directory: ./indexer

      - name: Check for debug flags
        run: |
          if grep -qi "DEBUG_SKIP_REBUILD_BALANCES = True" ./indexer/.env; then
            echo "::error::DEBUG_SKIP_REBUILD_BALANCES is set to True. This should be False in production code."
            exit 1
          fi
          echo "Debug flag check passed"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/indexer/src:${{ github.workspace }}/indexer" >> $GITHUB_ENV

      - name: Check import order with isort
        run: poetry run isort . --check-only
        working-directory: ./indexer

      - name: Format check with Black
        run: poetry run black --check . --config=pyproject.toml
        working-directory: ./indexer

      - name: Lint with flake8
        run: |
          poetry run flake8 src/ --count --statistics --exit-zero
        working-directory: ./indexer

      - name: Check Rust code
        working-directory: ./indexer
        run: poetry run check-rust

      - name: Security check with Bandit
        run: poetry run task bandit
        working-directory: ./indexer

      - name: Check with mypy
        run: poetry run mypy . --explicit-package-bases 
        working-directory: ./indexer

      - name: Run Tests
        working-directory: ./indexer
        env:
          PYTHONPATH: ${{ github.workspace }}/indexer/src:${{ github.workspace }}/indexer
          USE_TEST_TX_HEX: "1"
          TESTING: "1"
        run: |
          # Run all tests using Poetry scripts
          poetry run check-code
