name: Python Check

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  setup:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    uses: ./.github/workflows/reusable-setup.yml
    with:
      python-version: ${{ matrix.python-version }}

  python-check:
    needs: setup
    runs-on: ubuntu-latest
    env:
      USE_TEST_TX_HEX: '1'

    steps:
      - uses: actions/checkout@v4

      - name: Check for debug flags
        run: |
          if grep -qi "DEBUG_SKIP_REBUILD_BALANCES = True" ./indexer/.env; then
            echo "::error::DEBUG_SKIP_REBUILD_BALANCES is set to True. This should be False in production code."
            exit 1
          fi
          echo "Debug flag check passed"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/indexer/src:${{ github.workspace }}/indexer" >> $GITHUB_ENV

      - name: Check import order with isort
        run: poetry run isort . --check-only
        working-directory: ./indexer

      - name: Format check with Black
        run: poetry run black --check . --config=pyproject.toml
        working-directory: ./indexer

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ./indexer

      - name: Check Rust formatting
        working-directory: ./indexer/src/rust_parser
        run: cargo fmt -- --check

      - name: Run Rust clippy
        working-directory: ./indexer/src/rust_parser
        run: cargo clippy -- -D warnings

      - name: Security check with Bandit
        run: poetry run task bandit
        working-directory: ./indexer

      - name: Check with mypy
        run: poetry run mypy . --explicit-package-bases 
        working-directory: ./indexer

      # Run all the test suites
      - name: Run Test Suites
        working-directory: ./indexer
        run: |
          poetry run python3 -m unittest discover -s . -p "test_src20.py"
          poetry run python3 -m unittest discover -s . -p "test_check_format.py"
          poetry run python3 -m unittest discover -s . -p "test_arc4.py"
          poetry run python3 -m unittest discover -s . -p "test_transactions.py"
          poetry run pytest tests/test_src20_balance.py -v
          poetry run pytest tests/test_src20_update_valid.py -v
          poetry run pytest tests/test_src20_validator.py -v
        env:
          PYTHONPATH: ${{ github.workspace }}/indexer/src:${{ github.workspace }}/indexer
