name: Reusable Setup

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-poetry.outputs.cache-hit }}
    
    steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
        env:
          POETRY_HOME: ${{ github.workspace }}/.poetry

      - name: Add Poetry to PATH
        run: echo "${{ github.workspace }}/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies using Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install
        working-directory: ./indexer

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust parser
        working-directory: ./indexer
        run: |
          pip install maturin
          maturin develop --release 